### ISSUE TITLE
TODO Notes:

### ISSUE THREAD

**Issue by kumavis** [kumavis/hyper-prompt#1]
- [ ] fix chat history context
- [ ] multiline prompts
- [ ] optimize system prompt
- [ ] loading indicator
- [ ] browser navigation and tabs
- [ ] mind map mode
- [ ] model selection
- [ ] windowai/fren support
- [ ] save/share prompt result
